/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Comment = IDL.Record({ 'name' : IDL.Text, 'message' : IDL.Text });

export const idlService = IDL.Service({
  'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisitorCount' : IDL.Func([], [IDL.Nat], []),
  'submitComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Comment = IDL.Record({ 'name' : IDL.Text, 'message' : IDL.Text });
  
  return IDL.Service({
    'getAllComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisitorCount' : IDL.Func([], [IDL.Nat], []),
    'submitComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };